--- 
version: "3"
services: 
  cart: 
    container_name: cart
    depends_on: 
      - discovery
      - pg-docker
      - redis
      - gateway
    image: eallanjoseph/menu-cart
    links: 
      - discovery
      - pg-docker
      - redis
    ports: 
      - "8888:8888"
  discovery: 
    container_name: discovery
    image: eallanjoseph/menu-discovery
    ports: 
      - "8010:8010"
  gateway: 
    container_name: gateway
    depends_on: 
      - discovery
    image: eallanjoseph/menu-gateway
    links: 
      - discovery
    ports: 
      - "8999:8999"
  pg-docker: 
    container_name: pg-docker
    env_file: 
      - database-postgre.env
    image: postgres
    ports: 
      - "5432:5432"
    volumes: 
      - "/home/allan/workspace/docker/db/posgre:/var/lib/postgresql/data"
  redis: 
    container_name: redis
    image: redis
    ports: 
      - "6379:6379"

