---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
  application:
    name: cart
      
  jpa:  
    hibernate:  
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
  datasource:  
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres  
    password: docker
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: HikariPoolZZZ  

        
server:
  port: 1234  

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
      

 
 